version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/fserv
    binary: fserv
    env:
      - CGO_ENABLED=0
    ldflags:
      - -w -s
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      # arm (32-bit) only targeted for linux
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      # windows on arm64 is uncommon for this tool
      - goos: windows
        goarch: arm64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

release:
  draft: false

changelog:
  use: github
